# Generated by Django 4.1.7 on 2023-03-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0003_alter_weddingevent_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weddingevent',
            name='gender',
            field=models.CharField(choices=[('D', 'اختر الجنس'), ('MALE', ' ذكر'), ('FEMALE', ' أنثى')], default='D', max_length=10),
        ),
    ]
