# Generated by Django 4.1.7 on 2023-03-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0006_alter_weddingevent_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weddingevent',
            name='gender',
            field=models.CharField(choices=[('D', ''), ('Bride', ' Bride'), ('Groom', ' Groom')], default='D', max_length=10),
        ),
    ]
