# Generated by Django 4.1.7 on 2023-03-22 17:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('wedding', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('vendors_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('contact', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('category', models.ManyToManyField(related_name='category_vendor', to='vendors.category')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('category', models.ManyToManyField(related_name='category_serves', to='vendors.category')),
                ('vendors', models.ForeignKey(default='services_vendor', on_delete=django.db.models.deletion.CASCADE, related_name='vendors_services', to='vendors.vendors')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(blank=True, default=datetime.date.today)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors_booking', to='vendors.services')),
                ('wedding_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='wedding.weddingevent')),
            ],
        ),
    ]
