# Generated by Django 4.1.7 on 2023-03-21 11:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wedding', '0007_alter_weddingevent_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('booking_date', models.DateField(blank=True, default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('contact', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('vendors_user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='vedors_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('booking', models.ManyToManyField(related_name='booking_services', to='vendors.booking')),
                ('vendors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors_services', to='vendors.vendors')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='vendors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors_booking', to='vendors.vendors'),
        ),
        migrations.AddField(
            model_name='booking',
            name='wedding_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='wedding.weddingevent'),
        ),
    ]
