# Generated by Django 4.1.7 on 2023-03-16 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='vendors',
            field=models.ForeignKey(default='services_vendor', on_delete=django.db.models.deletion.CASCADE, related_name='vendors_services', to='vendors.vendors'),
        ),
    ]
