# Generated by Django 4.1.7 on 2023-03-22 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0002_vendors_id_alter_vendors_vendors_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendors',
            name='vendors_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to=settings.AUTH_USER_MODEL),
        ),
    ]
