# Generated by Django 4.1.7 on 2023-03-18 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_alter_services_vendors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='service',
        ),
    ]
