# Generated by Django 4.1.7 on 2023-03-19 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_remove_booking_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendors',
            name='price',
        ),
    ]
