# Generated by Django 4.1.7 on 2023-03-23 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0003_alter_vendors_vendors_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendors',
            name='id',
        ),
        migrations.AlterField(
            model_name='vendors',
            name='vendors_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='vendor', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
