# Generated by Django 4.1.7 on 2023-03-20 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_remove_vendors_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='vendors',
            field=models.ForeignKey(default='category_vendor', on_delete=django.db.models.deletion.CASCADE, related_name='vendors_category', to='vendors.vendors'),
        ),
    ]
