# Generated by Django 4.1.7 on 2023-03-20 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_remove_category_vendors_vendors_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendors',
            name='category',
        ),
        migrations.AddField(
            model_name='vendors',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vendors_category', to='vendors.category'),
            preserve_default=False,
        ),
    ]
