# Generated by Django 4.1.7 on 2023-03-21 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0007_alter_weddingevent_gender'),
        ('vendors', '0007_remove_vendors_category_vendors_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='price',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='vendors',
        ),
        migrations.RemoveField(
            model_name='services',
            name='booking',
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vendors_booking', to='vendors.services'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='wedding_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='wedding.weddingevent'),
        ),
        migrations.RemoveField(
            model_name='vendors',
            name='category',
        ),
        migrations.AddField(
            model_name='vendors',
            name='category',
            field=models.ManyToManyField(related_name='category_vendor', to='vendors.category'),
        ),
    ]
