# Generated by Django 4.1.7 on 2023-03-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_remove_booking_price_remove_booking_vendors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='category',
            field=models.ManyToManyField(related_name='category_serves', to='vendors.category'),
        ),
    ]
